version: "3"
services:
  app:
    container_name: oroshi_api
    build: .
    environment:
      FLASK_ENV: development
    ports:
      - "3030:5000"
    volumes:
      - ./app:/usr/src/app
    # command: flask run --host=0.0.0.0 --debugger --reload